import ChatOutputItem from "../../io/output/ChatOutputItem";
import ResponseStatistics from "../../statistics/ResponseStatistics";

/**
 * Full response returned by the model chat endpoint.
 */
type SendMessageResult = {
  /**
   * Unique identifier for the loaded model instance
   * that generated this response.
   */
  model_instance_id: string;

  /**
   * Array of output items generated by the model.
   * Includes messages, tool calls, reasoning, and errors.
   */
  output: ChatOutputItem[];

  /**F
   * Token usage and performance metrics.
   */
  stats: ResponseStatistics;

  /**
   * Identifier of the response for follow-up requests.
   * Present only when `store` is enabled.
   */
  response_id?: string;
}

export default SendMessageResult; 