/**
 * A standard text message generated by the model or sent as input in the chat conversation.
 */
type ChatTextMessage = {
  /**
   * Type of output item.
   */
  type: "text";

  /**
   * Text content of the message.
   */
  content: string;
}

export default ChatTextMessage; 
