/**
 * A standard image generated by the model or sent as input in the chat conversation.
 */
type ChatImageMessage = {
  /**
   * Type of input item.
   * Always "image" for image inputs.
   */
  type: "image";

  /**
   * Image data encoded as a base64 data URL.
   * Example: "data:image/png;base64,..."
   */
  data_url: string;
}

export default ChatImageMessage;